---
title: "Week 10 Problem Set: Census Data"
author: "Kaylynn Hiller"
date: "`r Sys.Date()`"
format:
  html: default
  pdf: default
---

```{r}
##My Examples with Census Data

library(tidycensus)
library(tidyverse)
library(scales)
options(tigris_use_cache = TRUE)

NC <- get_acs(
  state = "NC",
  geography = "county",
  variables = "B01001_026",
  geometry = TRUE,
  year = 2021
)

head(NC)

NC <- NC %>% mutate(NAME = str_replace_all(NAME," County, North Carolina", ""))

head(NC)

NC <- NC %>% rename(County = NAME)

head(NC)

NC %>%
  ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  scale_fill_continuous(labels=function(x) format(x, big.mark = ",", scientific = FALSE), name = "Total Females") +
  labs(title = "Total Females per NC County, 2017 - 2021")

NC %>%
  ggplot(aes(x = estimate, y = reorder(County, estimate))) + 
  geom_point(color = "steelblue") +
  labs(title = "Total Females per NC County, 2017 - 2021", x = "Total Females per County", y = "County") + 
  scale_x_continuous(labels = label_comma())

NC %>%
  ggplot(aes(x = estimate, y = reorder(County, estimate))) + 
  geom_col(color = "white", fill = "steelblue") +
  labs(title = "Total Females per NC County, 2017 - 2021", x = "Total Females per County", y = "County") + 
  scale_x_continuous(labels = label_comma())
```

**Examples from Readings:**

```{r}
##Basic usage of tidycensus

library(tidycensus)
library(sf)
library(tidyverse)

age20 <- get_decennial(geography = "state", 
                       variables = "P13_001N", 
                       year = 2020,
                       sumfile = "dhc")

head(age20)

age20 %>%
  ggplot(aes(x = value, y = reorder(NAME, value))) + 
  geom_point()

v17 <- load_variables(2017, "acs5", cache = TRUE)

vt <- get_acs(geography = "county", 
              variables = c(medincome = "B19013_001"), 
              state = "VT", 
              year = 2021)

vt

vt %>%
  mutate(NAME = gsub(" County, Vermont", "", NAME)) %>%
  ggplot(aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point(color = "red", size = 3) +
  labs(title = "Household income by county in Vermont",
       subtitle = "2017-2021 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)")

```

```{r}
##Spatial data in tidycensus

library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)

orange <- get_acs(
  state = "CA",
  county = "Orange",
  geography = "tract",
  variables = "B19013_001",
  geometry = TRUE,
  year = 2020
)

head(orange)

orange %>%
  ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma") 

racevars <- c(White = "P2_005N", 
              Black = "P2_006N", 
              Asian = "P2_008N", 
              Hispanic = "P2_002N")

harris <- get_decennial(
  geography = "tract",
  variables = racevars,
  state = "TX",
  county = "Harris County",
  geometry = TRUE,
  summary_var = "P2_001N",
  year = 2020,
  sumfile = "pl"
) 

head(harris)

harris %>%
  mutate(percent = 100 * (value / summary_value)) %>%
  ggplot(aes(fill = percent)) +
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  theme_void() + 
  scale_fill_viridis_c() + 
  labs(fill = "% of population\n(2020 Census)")

library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)

ny <- get_acs(geography = "tract", 
              variables = "B19013_001", 
              state = "NY", 
              county = "New York", 
              year = 2020, 
              geometry = TRUE)

ggplot(ny, aes(fill = estimate)) + 
  geom_sf() + 
  theme_void() + 
  scale_fill_viridis_c(labels = scales::dollar)

library(tigris)
library(sf)

ny_erase <- get_acs(
  geography = "tract",
  variables = "B19013_001",
  state = "NY",
  county = "New York",
  year = 2020,
  geometry = TRUE,
  cb = FALSE
) %>%
  st_transform(26918) %>%
  erase_water(year = 2020)

ggplot(ny_erase, aes(fill = estimate)) + 
  geom_sf() + 
  theme_void() + 
  scale_fill_viridis_c(labels = scales::dollar)
```

```{r}
##Margins of error in the ACS

library(tidycensus)
library(tidyverse)

vars <- paste0("B01001_0", c(20:25, 44:49))

ramsey <- get_acs(geography = "tract", 
                  variables = vars, 
                  state = "MN", 
                  county = "Ramsey", 
                  year = 2016)

head(ramsey %>% select(-NAME))

ramsey65 <- ramsey %>%
  group_by(GEOID) %>%
  summarize(sumest = sum(estimate), 
            summoe = moe_sum(moe, estimate))

head(ramsey65)
```

```{r}
##Other Census Bureau datasets

library(tidycensus)
library(tidyverse)
library(tigris)
options(tigris_use_cache = TRUE)

us_components <- get_estimates(geography = "state", product = "components", vintage = 2024)

us_components

unique(us_components$variable)

net_migration <- get_estimates(geography = "county",
                               variables = "RNETMIG",
                               vintage = 2024,
                               geometry = TRUE,
                               resolution = "20m") %>%
  shift_geometry()

net_migration

library(showtext)
font_add_google("Roboto")
showtext_auto()

order = c("-15 and below", "-15 to -5", "-5 to +5", "+5 to +15", "+15 and up")

net_migration <- net_migration %>%
  mutate(groups = case_when(
    value > 15 ~ "+15 and up",
    value > 5 ~ "+5 to +15",
    value > -5 ~ "-5 to +5",
    value > -15 ~ "-15 to -5",
    TRUE ~ "-15 and below"
  )) %>%
  mutate(groups = factor(groups, levels = order))

state_overlay <- states(
  cb = TRUE,
  resolution = "20m"
) %>%
  filter(GEOID != "72") %>%
  shift_geometry()

ggplot() +
  geom_sf(data = net_migration, aes(fill = groups, color = groups), size = 0.1) +
  geom_sf(data = state_overlay, fill = NA, color = "black", size = 0.1) +
  scale_fill_brewer(palette = "PuOr", direction = -1) +
  scale_color_brewer(palette = "PuOr", direction = -1, guide = FALSE) +
  coord_sf(datum = NA) +
  theme_minimal(base_family = "Roboto", base_size = 18) +
  labs(title = "Net migration per 1000 residents by county",
       subtitle = "US Census Bureau 2024 Population Estimates",
       fill = "Rate",
       caption = "Data acquired with the R tidycensus package | @kyle_e_walker")

la_age_hisp <- get_estimates(geography = "county", 
                             product = "characteristics", 
                             breakdown = c("SEX", "AGEGROUP", "HISP"),  
                             breakdown_labels = TRUE, 
                             state = "CA", 
                             county = "Los Angeles",
                             vintage = 2024)

la_age_hisp

compare <- filter(la_age_hisp, str_detect(AGEGROUP, "^Age"), 
                  HISP != "Both Hispanic Origins", 
                  SEX != "Both sexes") %>%
  mutate(value = ifelse(SEX == "Male", -value, value))

ggplot(compare, aes(x = AGEGROUP, y = value, fill = SEX)) + 
  geom_bar(stat = "identity", width = 1) + 
  theme_minimal(base_family = "Roboto") + 
  scale_y_continuous(labels = function(y) paste0(abs(y / 1000), "k")) + 
  scale_x_discrete(labels = function(x) gsub("Age | years", "", x)) + 
  scale_fill_manual(values = c("darkred", "navy")) + 
  coord_flip() + 
  facet_wrap(~HISP) + 
  labs(x = "", 
       y = "2024 Census Bureau population estimate", 
       title = "Population structure by Hispanic origin", 
       subtitle = "Los Angeles County, California", 
       fill = "", 
       caption = "Data source: US Census Bureau population estimates & tidycensus R package")

wch_flows <- get_flows(
  geography = "county",
  state = "NY",
  county = "Westchester",
  year = 2018
  )

wch_flows %>% 
  filter(!is.na(GEOID2)) %>% 
  head()

wch_flows %>% 
  filter(variable == "MOVEDOUT") %>% 
  arrange(desc(estimate)) %>% 
  head()

wch_flows %>% 
  filter(variable == "MOVEDNET") %>% 
  arrange(estimate) %>% 
  head()

wch_flows %>% 
  filter(is.na(GEOID2)) %>% 
  head()

la_flows <- get_flows(
  geography = "metropolitan statistical area",
  breakdown = "RACE",
  breakdown_labels = TRUE,
  msa = 31080,   # los angeles msa fips code
  year = 2015
  )

# net migration between la and san francisco
la_flows %>% 
  filter(str_detect(FULL2_NAME, "San Fran"), variable == "MOVEDNET")

phx_flows <- get_flows(
  geography = "metropolitan statistical area",
  msa = 38060,
  year = 2018,
  geometry = TRUE
  )

phx_flows %>% 
  head()

library(mapdeck)

top_move_in <- phx_flows %>% 
  filter(!is.na(GEOID2), variable == "MOVEDIN") %>% 
  slice_max(n = 25, order_by = estimate) %>% 
  mutate(
    width = estimate / 500,
    tooltip = paste0(
      scales::comma(estimate * 5, 1),
      " people moved from ", str_remove(FULL2_NAME, "Metro Area"),
      " to ", str_remove(FULL1_NAME, "Metro Area"), " between 2014 and 2018"
      )
    )

top_move_in %>% 
  mapdeck(style = mapdeck_style("dark"), pitch = 45) %>% 
  add_arc(
    origin = "centroid1",
    destination = "centroid2",
    stroke_width = "width",
    auto_highlight = TRUE,
    highlight_colour = "#8c43facc",
    tooltip = "tooltip"
  )
```
